export const siteLinks = {
  home: "/",
  product: "/#how-it-works",
  nox: "/#nox",
  applications: "/#applications",
  security: "/#why-conclave",
  demo: "/#demo",
  faq: "/#faq",
  login: "/auth/login",
  signup: "/auth/signup",
  privacy: "/privacy",
  terms: "/terms",
  documentation: "https://docs.iex.ec/",
  iexec: "https://www.iex.ec/",
} as const;
