// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IResultVerifier$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IResultVerifier";
  readonly sourceName: "contracts/verify/IResultVerifier.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes32","name":"campaignId","type":"bytes32"},{"internalType":"bytes32","name":"resultHash","type":"bytes32"},{"internalType":"bytes32","name":"taskId","type":"bytes32"},{"internalType":"bytes","name":"proof","type":"bytes"}],"name":"verifyResult","outputs":[{"internalType":"bool","name":"ok","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/verify/IResultVerifier.sol";
  readonly buildInfoId: "solc-0_8_28-b07fc1ff12f2d7820bda0fadb57744d79db673b8";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IResultVerifier"]: IResultVerifier$Type;
    ["contracts/verify/IResultVerifier.sol:IResultVerifier"]: IResultVerifier$Type;
  }
}